export enum EstadoPasajero {
  FACTURANDO_EQUIPAJE,
  ESPERANDO_FACTURACION,
  EN_CONTROL_METALES,
  ESPERANDO_CONTROL,
  COMPRANDO_BILLETE,
  ESPERANDO_COMPRA_BILLETE,
  CHEQUEANDO_BILLETE,
  ESPERANDO_CHEQUEO_BILLETE,
  PASANDO_DE_VENTA_A_FACTURACION,
  PASANDO_DE_FACTURACION_A_CONTROL,
  PASANDO_DE_CHEQUEO_BILLETE_A_CONTROL,
  PASANDO_DE_CONTROL_A_EMBARQUE,
  BLOQUEADO_EN_ENTRADA,
  BLOQUEADO_EN_CHEQUEO
}